jcraigk/phishin

db/migrate/20181214074204_add_timestamps_to_tags.rb
db/schema.rb
spec/factories/track_tag.rb

Add timestamps to TrackTag

---

app/views/shared/_context_menu_for_track.html.slim
spec/features/show_spec.rb
spec/features/top_40_spec.rb
spec/features/track_context_menus_spec.rb

Show all songs in track context dropdown

---

app/controllers/api/v1/api_controller.rb
app/controllers/concerns/api_auth.rb
app/models/api_key.rb
app/views/static_pages/api_docs.html.slim
db/migrate/20181218053555_create_api_keys.rb
db/schema.rb
spec/api/v1/api_controller_spec.rb
spec/api/v1/eras_controller_spec.rb
spec/api/v1/playlists_controller_spec.rb
spec/api/v1/search_controller_spec.rb
spec/api/v1/shows_controller_spec.rb
spec/api/v1/songs_controller_spec.rb
spec/api/v1/tags_controller_spec.rb
spec/api/v1/tours_controller_spec.rb
spec/api/v1/tracks_controller_spec.rb
spec/api/v1/venues_controller_spec.rb
spec/api/v1/years_controller_spec.rb
spec/factories/api_key.rb
spec/features/top_40_spec.rb
spec/models/api_key_spec.rb
spec/rails_helper.rb
spec/support/auth_helper.rb

Add API Keys

---

app/models/playlist.rb
app/models/show.rb
app/models/song.rb
app/models/tag.rb
app/models/tour.rb
app/models/track.rb
app/models/venue.rb
app/views/shows/show.html.slim
spec/api/v1/search_controller_spec.rb
spec/models/playlist_spec.rb
spec/models/show_spec.rb
spec/models/song_spec.rb
spec/models/tag_spec.rb
spec/models/tour_spec.rb
spec/models/track_spec.rb
spec/models/venue_spec.rb

Convert dates to ISO8601 during JSON serialization

---

app/controllers/concerns/ambiguity/tour_name.rb
app/controllers/concerns/ambiguity/year.rb
app/controllers/concerns/ambiguity/year_range.rb
app/models/show.rb
app/models/venue.rb
db/migrate/20181221071531_add_venue_name_to_shows.rb
db/schema.rb
spec/factories/playlist.rb
spec/factories/tour.rb
spec/factories/venue_rename.rb
spec/models/show_spec.rb
spec/models/venue_spec.rb

Cache venue_name on show

---

.rubocop.yml
app/controllers/api/v1/search_controller.rb
app/controllers/search_controller.rb
app/services/date_parser.rb
app/services/search_service.rb
app/views/search/_error.html.slim
app/views/search/_no_results.html.slim
app/views/search/_results_exact_show.html.slim
app/views/search/_results_other_shows.html.slim
app/views/search/_results_show_tags.html.slim
app/views/search/_results_songs.html.slim
app/views/search/_results_tags.html.slim
app/views/search/_results_tours.html.slim
app/views/search/_results_track_tags.html.slim
app/views/search/_results_venues.html.slim
app/views/search/results.html.slim
config/initializers/app_constants.rb
config/locales/en.yml
spec/api/v1/search_controller_spec.rb
spec/features/search_spec.rb
spec/services/date_parser_spec.rb
spec/services/search_service_spec.rb
spec/support/feature_helpers.rb

Add tags to search results, add specs

---

README.md
app/models/track.rb
app/services/track_slug_generator.rb
config/database.yml
lib/show_importer/cli.rb
lib/show_importer/orchestrator.rb
lib/show_importer/track_proxy.rb
lib/tasks/tracks.rake
spec/factories/playlist.rb
spec/factories/song.rb
spec/factories/tag.rb
spec/factories/tour.rb
spec/factories/track.rb
spec/factories/venue.rb
spec/factories/venue_rename.rb
spec/models/show_spec.rb
spec/models/track_spec.rb
spec/services/track_slug_generator_spec.rb

* Extract slug generation into service
* Fix multi-show import process
* Allow database connection inside and outside of docker
* Add `tracks:apply_id3` rake task

Show importer improvements

---

app/services/jamcharts_importer.rb
lib/tasks/phishnet.rake

Refactor phishnet jamcharts import

---

app/assets/javascripts/classes/player.js.coffee
app/helpers/application_helper.rb
app/models/track.rb
app/views/shows/show.html.slim
config/initializers/app_constants.rb

Allow anchoring to sets on show pages

---

README.md
app/views/songs/index.html.slim
app/views/songs/show.html.slim
db/migrate/20181226072534_add_original_to_songs.rb
db/schema.rb

Add cover/original indicator to Songs

---

app/assets/javascripts/application.js.coffee
app/controllers/api/v1/api_controller.rb
app/controllers/concerns/api_auth.rb
app/models/api_key.rb
app/models/api_request.rb
app/views/map/index.html.slim
db/migrate/20181228035420_create_api_requests.rb
db/schema.rb
spec/api/v1/api_controller_spec.rb
spec/factories/api_request.rb
spec/models/api_key_spec.rb
spec/models/api_request.rb
spec/models/like_spec.rb
spec/models/playlist_bookmark_spec.rb
spec/models/playlist_spec.rb
spec/models/playlist_track_spec.rb
spec/models/show_spec.rb
spec/models/show_tag_spec.rb
spec/models/song_spec.rb
spec/models/songs_track_spec.rb
spec/models/tag_spec.rb
spec/models/tour_spec.rb
spec/models/track_spec.rb
spec/models/track_tag_spec.rb
spec/models/venue_rename.rb
spec/models/venue_spec.rb

Log api requests

---

app/assets/javascripts/classes/map.js.coffee
app/views/layouts/application.html.slim

Fix Google Map API integration

---

MIT-LICENSE
README.md

Add MIT License and StreamPhish contribution

---

README.md
app/assets/javascripts/application.js.coffee
app/assets/javascripts/classes/player.js.coffee
config/initializers/app_constants.rb

Add Shift-Arrow shortcut to scrub, app content config

---

app/models/show.rb
app/models/tag.rb
app/models/track.rb
spec/features/tags_spec.rb
spec/features/track_context_menus_spec.rb
spec/models/show_spec.rb
spec/models/tag_spec.rb
spec/models/track_spec.rb

Improve Tag data in API

---

app/services/show_importer/track_replacer.rb

Fix show replacement when song appears multiple times

---

app/assets/stylesheets/application.css.scss
app/controllers/map_controller.rb
app/views/map/index.html.slim

Rescue map time param parsing, tweak CSS

---

app/assets/stylesheets/application.css.scss
app/controllers/concerns/ambiguity/song_title.rb
app/helpers/application_helper.rb
app/models/song.rb
app/services/search_service.rb
app/views/search/_results_songs.html.slim
app/views/songs/index.html.slim
app/views/songs/show.html.slim
app/views/static_pages/api_docs.html.slim
db/migrate/20190803193249_add_alias_to_songs.rb
db/migrate/20190803193740_drop_alias_for_from_songs.rb
db/schema.rb
spec/factories/song.rb
spec/features/ambiguous_slug_spec.rb
spec/features/songs_spec.rb
spec/models/song_spec.rb

Improve song aliasing

---

README.md
app/assets/javascripts/application.js.coffee
app/assets/javascripts/classes/player.js.coffee
app/views/devise/mailer/confirmation_instructions.html.slim
app/views/errors/browser_unsupported.html.slim
app/views/layouts/_page_footer.html.slim
app/views/static_pages/tagin_project.html.slim
config/initializers/app_constants.rb
spec/features/homepage_spec.rb

Update page title on track play, remove apostrophes from app name

---

app/services/show_importer/track_proxy.rb

Fix set detection on show import

---

.rubocop.yml
.travis.yml
Dockerfile
Gemfile
Gemfile.lock
README.md

* Downgrade Ruby to 2.6.6 (2.7.1 has too many warnings)
* Bundle update
* Update Dev Pack link in README

Downgrade Ruby to 2.6.6

---

nginx.conf.sigil

I think this should fix the problem I'm having:

Allow Authorization for browser preflight

---

.travis.yml
config/application.rb
db/migrate/20210411223309_create_active_storage_tables.active_storage.rb
db/schema.rb

Prep for conversion of Paperclip disk-based storage to ActiveStorage S3-based.

Add active_storage create migration

---

app/assets/javascripts/classes/player.js.coffee
app/assets/stylesheets/application.css.scss

Fix JS setVolume error

---

app/assets/javascripts/app-main.js.coffee
app/assets/javascripts/classes/map.js.coffee
app/assets/stylesheets/application.css.scss
app/views/layouts/application.html.slim
app/views/map/index.html.slim
spec/features/map_spec.rb

Replace Google Maps with Mapbox

---

app/assets/stylesheets/application.css.scss
app/controllers/concerns/ambiguity/song_title.rb
app/controllers/my_controller.rb
app/controllers/tags_controller.rb
app/helpers/navigation_helper.rb
app/views/my/my_shows.html.slim
app/views/my/my_tracks.html.slim
app/views/songs/show.html.slim
app/views/tags/show.html.slim

Add pagination links for all on single page

---

app/controllers/concerns/ambiguity/day_of_year.rb
app/helpers/navigation_helper.rb
config/initializers/app_constants.rb
spec/features/ambiguous_slug_spec.rb
spec/rails_helper.rb

Add /today page for day of month in history

---

app/assets/javascripts/app-main.js.coffee
app/helpers/application_helper.rb
app/helpers/track_helper.rb
app/models/song.rb
app/services/search_service.rb
app/views/layouts/application.html.slim
app/views/shared/_lyrics_modal.html.slim
app/views/songs/show.html.slim
db/migrate/20210503051354_add_lyrics_to_songs.rb
db/schema.rb
lib/tasks/songs.rake
spec/factories/song.rb
spec/models/song_spec.rb

Import lyrics, display via modal, include in search

---

app/controllers/feeds_controller.rb
app/models/announcement.rb
app/services/show_importer/orchestrator.rb
app/views/eras/index.html.slim
app/views/feeds/rss.xml.builder
config/initializers/app_constants.rb
config/routes.rb
db/migrate/20221224070950_create_announcements.rb
db/schema.rb
spec/factories/announcement.rb
spec/features/feeds_spec.rb

Add RSS feed

---

.travis.yml
Dockerfile
app.json
spec/features/player_spec.rb

Followup to https://github.com/jcraigk/phishin/pull/323. 
Add javascript dependencies to Dockerfile for compiling assets with Shakapacker.

Shakapacker support in Dockerfile for deploy

---

app/helpers/tag_helper.rb
app/javascript/packs/application.css.scss
app/javascript/src/coffeescript/app.js.coffee

Improve tooltips and dialogs

---

app/controllers/playlists_controller.rb
app/javascript/packs/application.css.scss
app/javascript/src/coffeescript/app.js.coffee
app/javascript/src/coffeescript/player.js.coffee
app/javascript/src/coffeescript/playlist.js.coffee
app/views/layouts/_player_menu.html.slim
app/views/playlists/active.html.slim
config/routes.rb
spec/features/player_spec.rb

Fix playlist

---

app/javascript/src/coffeescript/player.js.coffee
app/views/layouts/_player.html.slim
app/views/songs/show.html.slim

Fix audio playback on iOS

---

app/api/api_v2/playlists.rb
app/javascript/components/DraftPlaylist.jsx
app/javascript/components/Tracks.jsx
app/javascript/components/controls/Player.jsx
app/javascript/components/controls/TrackInfo.jsx
app/javascript/components/hooks/useGaplessPlayer.js
app/models/playlist_track.rb

Fix playlist excerpts
